In [1]:
import pandas as pd

In [2]:
dfa = pd.read_csv("annual.csv")

In [3]:
dfa.shape

(41715, 10)

In [4]:
dfa

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41710,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41711,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41712,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41713,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
41714,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [5]:
dfa.columns

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')

In [8]:
dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41715 entries, 0 to 41714
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         41715 non-null  int64
 1   Industry_aggregation_NZSIOC  41715 non-null  object
 2   Industry_code_NZSIOC         41715 non-null  object
 3   Industry_name_NZSIOC         41715 non-null  object
 4   Units                        41715 non-null  object
 5   Variable_code                41715 non-null  object
 6   Variable_name                41715 non-null  object
 7   Variable_category            41715 non-null  object
 8   Value                        41715 non-null  object
 9   Industry_code_ANZSIC06       41715 non-null  object
dtypes: int64(1), object(9)
memory usage: 3.2+ MB

In [9]:
dfa['Industry_aggregation_NZSIOC'].nunique()

3

In [10]:
dfa['Industry_aggregation_NZSIOC'].unique()

array(['Level 1', 'Level 3', 'Level 4'], dtype=object)

In [11]:
dfa['Industry_aggregation_NZSIOC'].value_counts()

Level 4    22833
Level 3    13851
Level 1     5031
Name: Industry_aggregation_NZSIOC, dtype: int64

In [12]:
# dfa['Industry_aggregation_NZSIOC'] == 'Level 1'

dfa [ dfa['Industry_aggregation_NZSIOC'] == 'Level 1' ]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"757,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"674,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,404",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
41418,2013,Level 1,RS,"Arts, Recreation and Other Services",Percentage,H36,Current ratio,Financial ratios,147,ANZSIC06 divisions R and S
41419,2013,Level 1,RS,"Arts, Recreation and Other Services",Percentage,H37,Quick ratio,Financial ratios,137,ANZSIC06 divisions R and S
41420,2013,Level 1,RS,"Arts, Recreation and Other Services",Percentage,H39,Return on equity,Financial ratios,14,ANZSIC06 divisions R and S
41421,2013,Level 1,RS,"Arts, Recreation and Other Services",Percentage,H40,Return on total assets,Financial ratios,9,ANZSIC06 divisions R and S
41422,2013,Level 1,RS,"Arts, Recreation and Other Services",Percentage,H41,Liabilities structure,Financial ratios,69,ANZSIC06 divisions R and S

In [13]:
dfa_1 = dfa [ dfa['Industry_aggregation_NZSIOC'] == 'Level 1' ]

In [14]:
dfa_1.to_excel("level 1.xlsx", index=False)

In [15]:
dfa[11:30]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
11,2021,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"452,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...
14,2021,Level 1,99999,All industries,Dollars (millions),H22,Closing stocks,Financial performance,"69,127",ANZSIC06 divisions A-S (excluding classes K633...
15,2021,Level 1,99999,All industries,Dollars (millions),H23,Surplus before income tax,Financial performance,"103,330",ANZSIC06 divisions A-S (excluding classes K633...
16,2021,Level 1,99999,All industries,Dollars (millions),H24,Total assets,Financial position,"2,512,677",ANZSIC06 divisions A-S (excluding classes K633...
17,2021,Level 1,99999,All industries,Dollars (millions),H25,Current assets,Financial position,"730,587",ANZSIC06 divisions A-S (excluding classes K633...
18,2021,Level 1,99999,All industries,Dollars (millions),H26,Fixed tangible assets,Financial position,"591,351",ANZSIC06 divisions A-S (excluding classes K633...
19,2021,Level 1,99999,All industries,Dollars (millions),H29,Other assets,Financial position,"1,190,739",ANZSIC06 divisions A-S (excluding classes K633...
20,2021,Level 1,99999,All industries,Dollars (millions),H30,Total equity and liabilities,Financial position,"2,512,677",ANZSIC06 divisions A-S (excluding classes K633...
21,2021,Level 1,99999,All industries,Dollars (millions),H31,Shareholders funds or owners equity,Financial position,"813,949",ANZSIC06 divisions A-S (excluding classes K633...
22,2021,Level 1,99999,All industries,Dollars (millions),H32,Current liabilities,Financial position,"933,093",ANZSIC06 divisions A-S (excluding classes K633...
23,2021,Level 1,99999,All industries,Dollars (millions),H33,Other liabilities,Financial position,"765,635",ANZSIC06 divisions A-S (excluding classes K633...
24,2021,Level 1,99999,All industries,Dollars,H34,Total income per employee count,Financial ratios,"400,900",ANZSIC06 divisions A-S (excluding classes K633...
25,2021,Level 1,99999,All industries,Dollars,H35,Surplus per employee count,Financial ratios,"54,700",ANZSIC06 divisions A-S (excluding classes K633...
26,2021,Level 1,99999,All industries,Percentage,H36,Current ratio,Financial ratios,78,ANZSIC06 divisions A-S (excluding classes K633...
27,2021,Level 1,99999,All industries,Percentage,H37,Quick ratio,Financial ratios,71,ANZSIC06 divisions A-S (excluding classes K633...
28,2021,Level 1,99999,All industries,Percentage,H39,Return on equity,Financial ratios,13,ANZSIC06 divisions A-S (excluding classes K633...
29,2021,Level 1,99999,All industries,Percentage,H40,Return on total assets,Financial ratios,4,ANZSIC06 divisions A-S (excluding classes K633...

In [16]:
dfa['Units'].value_counts()

Dollars (millions)    32796
Percentage             6633
Dollars                2286
Name: Units, dtype: int64

In [17]:
help(dfa.value_counts)

Help on method value_counts in module pandas.core.frame:

value_counts(subset: 'Optional[Sequence[Label]]' = None, normalize: 'bool' = False, sort: 'bool' = True, ascending: 'bool' = False) method of pandas.core.frame.DataFrame instance
    Return a Series containing counts of unique rows in the DataFrame.

    .. versionadded:: 1.1.0

    Parameters
    ----------
    subset : list-like, optional
        Columns to use when counting unique combinations.
    normalize : bool, default False
        Return proportions rather than frequencies.
    sort : bool, default True
        Sort by frequencies.
    ascending : bool, default False
        Sort in ascending order.

    Returns
    -------
    Series

    See Also
    --------
    Series.value_counts: Equivalent method on Series.

    Notes
    -----
    The returned Series will have a MultiIndex with one level per input
    column. By default, rows that contain any NA values are omitted from
    the result. By default, the resulting Series will be in descending
    order so that the first element is the most frequently-occurring row.

    Examples
    --------
    >>> df = pd.DataFrame({'num_legs': [2, 4, 4, 6],
    ...                    'num_wings': [2, 0, 0, 0]},
    ...                   index=['falcon', 'dog', 'cat', 'ant'])
    >>> df
            num_legs  num_wings
    falcon         2          2
    dog            4          0
    cat            4          0
    ant            6          0

    >>> df.value_counts()
    num_legs  num_wings
    4         0            2
    2         2            1
    6         0            1
    dtype: int64

    >>> df.value_counts(sort=False)
    num_legs  num_wings
    2         2            1
    4         0            2
    6         0            1
    dtype: int64

    >>> df.value_counts(ascending=True)
    num_legs  num_wings
    2         2            1
    6         0            1
    4         0            2
    dtype: int64

    >>> df.value_counts(normalize=True)
    num_legs  num_wings
    4         0            0.50
    2         2            0.25
    6         0            0.25
    dtype: float64